import 'package:flutter/material.dart';
import 'package:help_med/model/models.dart';

import 'package:cloud_firestore/cloud_firestore.dart';

class DataRepository {
  String userid;
  late CollectionReference collection;

  DataRepository({required this.userid}) {
    collection = FirebaseFirestore.instance
        .collection('users')
        .doc(userid)
        .collection('profiles');
  }

  //Read all the Profiles
  Stream<QuerySnapshot> getStream() {
    return collection.snapshots();
  }

  //Read a single Profile with a given ID
  Future<DocumentSnapshot> getProfile(String profileID) {
    return collection.doc(profileID).get();
  }

  // Future<DocumentSnapshot> getProfileObject(String profileID) {
  //   return collection
  //       .doc(profileID)
  //       .withConverter(
  //         fromFirestore: Profile.fromFiresore,
  //         toFirestore: (Profile perfil, _) => perfil.toFirestore(),
  //       )
  //       .get();
  // }

  // Add a Profile with autogenerated ID
  Future<DocumentReference> addProfile(Profile profile) {
    return collection.add(profile.toFirestore());
  }

  Future<void> addProfileID(Profile profile) {
    return collection.doc(profile.id).set(profile.toFirestore());
  }

  // Add a Profile with a given ID
  void updateProfile(Profile profile) async {
    await collection.doc(profile.id).update(profile.toFirestore());
  }

  // Delete the profile
  void deleteProfile(Profile profile) async {
    await collection.doc(profile.id).delete();
  }
}

                          // final profileRef = db
                          //     .collection("users")
                          //     .doc(userid)
                          //     .collection("profiles")
                          //     .doc('1725161051')
                          //     .withConverter(
                          //       fromFirestore: Profile.fromFiresore,
                          //       toFirestore: (Profile perfil, _) =>
                          //           perfil.toFirestore(),
                          //     );

                          // //Profile profile = await profileRef.get().then((s) => s.data());

                          // final docSnap = await profileRef.get();
                          // Profile profile =
                          //     docSnap.data(); // Convert to Profile object
                          // if (profile != null) {
                          //   print(profile);
                          // } else {
                          //   print("No such document.");
                          // }

                          // final profileRef = db
                          //     .collection("users")
                          //     .doc(userid)
                          //     .collection("profiles")
                          //   .where("name", isEqualTo: perfil.name);







                                                    // FirebaseFirestore db = FirebaseFirestore.instance;

                          // Map<String, dynamic> data = medication.toMap();


                          // final profileRef = db
                          //     .collection('users')
                          //     .doc(userid)
                          //     .collection('profiles')
                          //     .doc('1725161051');

                          // profileRef.get().then(
                          //   (DocumentSnapshot doc) {
                          //     final data = doc.data() as Map<String, dynamic>;
                          //     print(data);
                          //   },
                          //   onError: (e) => print("Error getting document: $e"),
                          // );

                          // print("el id es......" + profileRef.id);

                          // //     .collection('medication')
                          // //     .doc(medication.name)
                          // //     .set(medication.toMap())
                          // // .onError((e, _) => print("Error writing document: $e"));